version: '3.8'

services:
  
  api:
    build:
      context: .
      target: development
      dockerfile: Dockerfile.test
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    env_file:
      - .env
    restart: on-failure
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "70:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 45s
      timeout: 15s
      retries: 2
    restart: on-failure

networks:
  app-network: